FROM node:24.20.0-bookworm-slim AS build
ARG FRONTEND_PROJECT
ARG STOREFRONT_ORIGIN=http://localhost:6300
ARG STOREFRONT_SITE=agoraApparelSite
ARG STOREFRONT_STORE=agoraMainStore
ARG STOREFRONT_DOMAIN=apparel
ARG STOREFRONT_CURRENCY=USD
ENV VITE_CUSTOMER_CSRF_COOKIE_NAME=nodics_docker_customer_csrf \
    VITE_STOREFRONT_CMS_BASE_URL=http://localhost:5314 \
    VITE_STOREFRONT_MEDIA_BASE_URL=http://localhost:5314 \
    VITE_STOREFRONT_PROFILE_BASE_URL=http://localhost:5300 \
    VITE_STOREFRONT_ENGAGEMENT_BASE_URL=http://localhost:5340 \
    VITE_STOREFRONT_COMMERCE_BASE_URL=${STOREFRONT_ORIGIN} \
    VITE_STOREFRONT_SITE_CODE=${STOREFRONT_SITE} \
    VITE_STOREFRONT_STORE_CODE=${STOREFRONT_STORE} \
    VITE_STOREFRONT_DOMAIN_CODE=${STOREFRONT_DOMAIN} \
    VITE_STOREFRONT_CURRENCY=${STOREFRONT_CURRENCY}
WORKDIR /workspace/frontend
COPY ${FRONTEND_PROJECT}/ ./
RUN npm ci --ignore-scripts
ENV AXIS_BACKOFFICE_BASE_URL=http://localhost:5300 \
    AXIS_LOCATION_BASE_URL=http://localhost:5380/nodics/locationMap \
    AXIS_WASTE_API_BASE_URL=http://localhost:5370/nodics/wasteApi \
    AXIS_ENTERPRISE_CODE=default \
    AXIS_PROJECT_CODE=nodics.kickoff \
    AXIS_CLIENT_CONTRACT_VERSION=1 \
    AXIS_REQUEST_TIMEOUT_MS=10000 \
    AXIS_BROWSER_SESSION_CSRF_COOKIE_NAME=nodics_docker_axis_csrf \
    AXIS_ASSISTANT_MAXIMUM_EVENT_BYTES=65536 \
    AXIS_ASSISTANT_RECONNECT_WINDOW_MS=120000 \
    AXIS_ASSISTANT_IDLE_TIMEOUT_MS=45000 \
    AXIS_DEV_HOST=0.0.0.0 \
    AXIS_DEV_PORT=4100 \
    AXIS_STRICT_PORT=true \
    AXIS_BUILD_SOURCEMAP=false \
    NEXUS_AXIS_BASE_URL=http://localhost:4100 \
    NEXUS_PLATFORM_BASE_URL=http://localhost:5300 \
    NEXUS_ENTERPRISE_CODE=default \
    NEXUS_DEFAULT_LOCALE=en \
    NEXUS_CHANNEL=web \
    NEXUS_CLIENT_CONTRACT_VERSION=1 \
    NEXUS_REQUEST_TIMEOUT_MS=10000 \
    NEXUS_CORPORATE_HOSTS=localhost,127.0.0.1 \
    NEXUS_CORPORATE_SITE=nexusCorporateSite \
    NEXUS_DEV_HOST=0.0.0.0 \
    NEXUS_DEV_PORT=4200 \
    NEXUS_STRICT_PORT=true \
    NEXUS_BUILD_SOURCEMAP=false
RUN npm run build

FROM nginx:1.29.8-alpine3.23
ARG NGINX_CONFIG=nginx.conf
COPY nodics.kickoff/envs/kickoffDockerLocal/docker/${NGINX_CONFIG} /etc/nginx/conf.d/default.conf
COPY --from=build /workspace/frontend/dist /usr/share/nginx/html
RUN chown -R nginx:nginx /usr/share/nginx/html /var/cache/nginx /var/run
USER nginx
