/**
 * @module kickoffLocal/platformServer/config/properties
 * @description Declares Local Platform composition and prerequisites for explicitly selected publication providers.
 * @layer config
 * @owner nodics.kickoff
 * @override Later deployment layers may narrow application selections without replacing framework preparation or owner authorization.
 */
module.exports = {
  profileRuntimeEnterpriseResolution: {
    enabled: true,
    callers: { $config: "replace", value: [{
      tenant: "default", principalEnterpriseCode: "default", serviceId: "apiAdmin",
      projectCode: "nodics.kickoff", environmentCode: "kickoffLocal", serverCode: "commerceServer",
      instanceCode: "kickoff-local-commerce-1", assignmentCode: "kickoff-local-commerce-runtime-deployment",
      enterpriseCodes: ["GREENPERKS_ONLINE", "GREENPERKS_RETAIL", "RENEWWORKS_REPAIR_REUSE", "LOOPCYCLE_RECYCLING"],
    }] },
  },
  profileCustomerEvidence: {
    enabled: true,
    callers: { $config: "replace", value: [{
      tenant: "default", principalEnterpriseCode: "default", enterpriseCode: "GREENPERKS_ONLINE",
      serviceId: "apiAdmin", projectCode: "nodics.kickoff", environmentCode: "kickoffLocal",
      serverCode: "wasteServer", instanceCode: "kickoff-local-waste-1",
      assignmentCode: "kickoff-local-waste-runtime-deployment",
    }] },
  },
  publish: { setup: { observation: {
    enabled: true, profilePlans: { circa: "circa-native-reviewed" },
  } } },
  dynamoEnabled: true,
  runtimePropertyGovernance: {
    persistence: { enabled: true },
  },
  profileTenantProvisioning: {
    localRuntimeRemoteModuleExtensions: ["commsApi"],
  },
  identityGovernance: {
    migration: {
      // Preserve the full canonical Platform permission set; add only exact-plan observation.
      localRuntimeDeploymentGrantPermissions: {
        $config: "replace",
        value: [
          "auth.internal.token.read",
          "auth.internal.token.read.anyTenant",
          "location.location.read",
          "profile.address.reference.read",
          "profile.enterprise.reference.read",
          "communication.request",
          "communication.verification.execute",
          "profile.enterprise.search",
          "profile.tenant.namespace.bind",
          "profile.customer.register",
          "loyalty.wallet.open",
          "loyalty.wallet.read",
          "media.evidence.read",
          "media.customer.upload",
          "media.customer.read",
          "import.release.validate",
          "import.core.run",
          "publish.lifecycle.create",
          "publish.lifecycle.view",
          "publish.lifecycle.validate",
          "publish.lifecycle.requestApproval",
          "commerce.product.publish",
          "publish.setup.observe"
        ],
      },
      assessment: {
        bootstrapReview: {
          enabled: {
            $config: "env",
            name: "NODICS_LOCAL_BOOTSTRAP_IDENTITY_REVIEW_ENABLED",
            type: "boolean",
            fallback: false,
          },
        },
      },
    },
  },
  // Local capture-only selection; installed owner qualification remains separate.
  enterpriseManagement: {
    setupContinuation: {
      inspectionQualified: {
        $config: "env",
        name: "NODICS_LOCAL_ENTERPRISE_SETUP_INSPECTION_QUALIFIED",
        type: "boolean",
        fallback: false,
      },
      privateGuardsQualified: {
        $config: "env",
        name: "NODICS_LOCAL_ENTERPRISE_SETUP_PRIVACY_QUALIFIED",
        type: "boolean",
        fallback: false,
      },
      resumeQualified: {
        $config: "env",
        name: "NODICS_LOCAL_ENTERPRISE_SETUP_RESUME_QUALIFIED",
        type: "boolean",
        fallback: false,
      },
    },
    registration: {
      inventoryQualified: {
        $config: "env",
        name: "NODICS_LOCAL_REGISTRATION_INVENTORY_QUALIFIED",
        type: "boolean",
        fallback: false,
      },
      assignmentClaimIndexQualified: {
        $config: "env",
        name: "NODICS_LOCAL_REGISTRATION_CLAIM_INDEX_QUALIFIED",
        type: "boolean",
        fallback: false,
      },
      enabled: {
        $config: "env",
        name: "NODICS_LOCAL_ENTERPRISE_ONBOARDING_ENABLED",
        type: "boolean",
        fallback: false,
      },
      mail: { allowInsecureLoopback: true },
    },
    accessAssignments: {
      registrationVerification: {
        enabled: {
          $config: "env",
          name: "NODICS_LOCAL_ENTERPRISE_ONBOARDING_ENABLED",
          type: "boolean",
          fallback: false,
        },
        allowInsecureLoopback: true,
      },
    },
  },
  profileEmployeeRecovery: {
    enabled: {
      $config: "env",
      name: "NODICS_LOCAL_ENTERPRISE_ONBOARDING_ENABLED",
      type: "boolean",
      fallback: false,
    },
    mail: { allowInsecureLoopback: true },
  },
  backofficeRegistration: {
    connectionName: "default",
  },
  backofficeApplicationInitialization: {
    dataReleaseTimeoutMs: 360000,
    operatorOrigin: "http://localhost:3100",
    runtimeRoleProfiles: {
      PLATFORM: {
        profiles: {
          circa: {
            preparation: {
              prerequisites: {
                $config: "replace",
                value: [
                  {
                    code: "product:productPublicationWorkflow",
                    kind: "Product publication approval workflow",
                    required: true,
                    trigger: "USER",
                    dataType: "init",
                    targetServer: "process",
                    targetRuntimeRole: "PROCESS",
                  },
                  {
                    code: "pricing:pricingPublicationWorkflow",
                    kind: "Pricing publication approval workflow",
                    required: true,
                    trigger: "USER",
                    dataType: "init",
                    targetServer: "process",
                    targetRuntimeRole: "PROCESS",
                  },
                  {
                    code: "tax:taxPublicationWorkflow",
                    kind: "Tax publication approval workflow",
                    required: true,
                    trigger: "USER",
                    dataType: "init",
                    targetServer: "process",
                    targetRuntimeRole: "PROCESS",
                  },
                  {
                    code: "promotion:promotionPublicationWorkflow",
                    kind: "Promotion publication approval workflow",
                    required: true,
                    trigger: "USER",
                    dataType: "init",
                    targetServer: "process",
                    targetRuntimeRole: "PROCESS",
                  },
                  {
                    code: "inventory:inventoryPublicationWorkflow",
                    kind: "Inventory publication approval workflow",
                    required: true,
                    trigger: "USER",
                    dataType: "init",
                    targetServer: "process",
                    targetRuntimeRole: "PROCESS",
                  },
                  {
                    code: "profile:commerceSetupPublisherRole",
                    kind: "Enterprise-scoped Commerce setup publisher role",
                    required: true,
                    trigger: "USER",
                    dataType: "core",
                    targetServer: "platformServer",
                    targetRuntimeRole: "PLATFORM",
                  },
                  {
                    code: "profile:commercePublicationStarterRole",
                    kind: "Existing Process start access for Commerce publication requesters",
                    required: true,
                    trigger: "USER",
                    dataType: "core",
                    targetServer: "platformServer",
                    targetRuntimeRole: "PLATFORM",
                  },
                  {
                    code: "profile:commerceCouponIssuerRole",
                    kind: "Enterprise-scoped coupon issuer role",
                    required: true,
                    trigger: "USER",
                    dataType: "core",
                    targetServer: "platformServer",
                    targetRuntimeRole: "PLATFORM",
                  },
                  {
                    code: "profile:commerceAxisRefundReviewerRole",
                    kind: "Axis access and refund review for predefined demo staff",
                    required: true,
                    trigger: "USER",
                    dataType: "core",
                    targetServer: "platformServer",
                    targetRuntimeRole: "PLATFORM",
                  },
                  {
                    code: "circa.ewaste:circaCommerceStaffAssignments",
                    kind: "Additive predefined roles for exact existing demo staff",
                    // Separate late batch: employees and role definitions must already exist.
                    order: 100,
                    required: true,
                    trigger: "USER",
                    dataType: "sample",
                    targetServer: "platformServer",
                    targetRuntimeRole: "PLATFORM",
                  },
                  {
                    code: "circa.ewaste:circaMerchantOutletAccess",
                    kind: "Existing demo merchant operators exact outlet scopes",
                    required: true,
                    trigger: "USER",
                    dataType: "sample",
                    targetServer: "platformServer",
                    targetRuntimeRole: "PLATFORM",
                  },
                  {
                    code: "circa.ewaste:circaDigitalOwnershipPolicies",
                    kind: "Original digital asset sale and refund policies",
                    required: true,
                    trigger: "USER",
                    dataType: "sample",
                    targetServer: "wasteServer",
                    targetRuntimeRole: "WASTE",
                  },
                  {
                    code: "circa.ewaste:circaAssetClassification",
                    kind: "Forward asset classification after original Commerce sources",
                    order: 110,
                    required: true,
                    trigger: "USER",
                    dataType: "sample",
                    targetServer: "commerceStaged",
                    targetRuntimeRole: "COMMERCE_STAGED",
                  },
                  {
                    code: "circa.ewaste:circaCatalogueCurrentPublicationPlan",
                    type: "GOVERNED_PUBLICATIONS",
                    kind: "Marketplace catalogue publication",
                    operatorEnterpriseCode: "GREENPERKS_ONLINE",
                    required: true,
                    trigger: "USER",
                    phase: "AFTER_PUBLICATION",
                    dataType: "sample",
                    targetServer: "commerceStaged",
                    targetRuntimeRole: "COMMERCE_STAGED",
                    publicationPlan: require("../../../../modules/circa.ewaste/data/sample-v001/publication/current-catalogue/records/publicationPlan.json"),
                  },
                  {
                    code: "circa.ewaste:circaAssetClassificationPublicationPlan",
                    type: "GOVERNED_PUBLICATIONS",
                    kind: "Optional corrected asset publication subset",
                    operatorEnterpriseCode: "GREENPERKS_ONLINE",
                    required: false,
                    trigger: "USER",
                    phase: "AFTER_PUBLICATION",
                    dataType: "sample",
                    targetServer: "commerceStaged",
                    targetRuntimeRole: "COMMERCE_STAGED",
                    publicationPlan: require("../../../../modules/circa.ewaste/data/sample-v001/asset-publication/records/publicationPlan.json"),
                  },
                  {
                    code: "circa.ewaste:circaGreenPerksPublicationPlan",
                    type: "GOVERNED_PUBLICATIONS",
                    kind: "GreenPerks issuer policy publication",
                    operatorEnterpriseCode: "GREENPERKS_RETAIL",
                    required: true,
                    trigger: "USER",
                    phase: "AFTER_PUBLICATION",
                    dataType: "sample",
                    targetServer: "commerceStaged",
                    targetRuntimeRole: "COMMERCE_STAGED",
                    publicationPlan: require("../../../../modules/circa.ewaste/data/sample-v001/publication/greenperks/records/publicationPlan.json"),
                  },
                  {
                    code: "circa.ewaste:circaRenewWorksPublicationPlan",
                    type: "GOVERNED_PUBLICATIONS",
                    kind: "RenewWorks issuer policy publication",
                    operatorEnterpriseCode: "RENEWWORKS_REPAIR_REUSE",
                    required: true,
                    trigger: "USER",
                    phase: "AFTER_PUBLICATION",
                    dataType: "sample",
                    targetServer: "commerceStaged",
                    targetRuntimeRole: "COMMERCE_STAGED",
                    publicationPlan: require("../../../../modules/circa.ewaste/data/sample-v001/publication/renewworks/records/publicationPlan.json"),
                  },
                  {
                    code: "circa.ewaste:circaLoopCyclePublicationPlan",
                    type: "GOVERNED_PUBLICATIONS",
                    kind: "LoopCycle issuer policy publication",
                    operatorEnterpriseCode: "LOOPCYCLE_RECYCLING",
                    required: true,
                    trigger: "USER",
                    phase: "AFTER_PUBLICATION",
                    dataType: "sample",
                    targetServer: "commerceStaged",
                    targetRuntimeRole: "COMMERCE_STAGED",
                    publicationPlan: require("../../../../modules/circa.ewaste/data/sample-v001/publication/loopcycle/records/publicationPlan.json"),
                  },
                  {
                    "code": "circa.ewaste:circaLocalDemoCreditRole",
                    "kind": "Circa Local demo credit role",
                    "order": 120,
                    "required": true,
                    "trigger": "USER",
                    "phase": "BEFORE_PUBLICATION",
                    "dataType": "sample",
                    "targetServer": "platformServer",
                    "targetRuntimeRole": "PLATFORM"
                  },
                  {
                    "code": "circa.ewaste:circaLocalDemoCreditStaffAssignment",
                    "kind": "Circa Local demo credit staff assignment",
                    "order": 121,
                    "required": true,
                    "trigger": "USER",
                    "phase": "BEFORE_PUBLICATION",
                    "dataType": "sample",
                    "targetServer": "platformServer",
                    "targetRuntimeRole": "PLATFORM"
                  },
                  {
                    "code": "circa.ewaste:circaLocalOpeningRole",
                    "kind": "Circa Local opening Inventory role",
                    "order": 122,
                    "required": true,
                    "trigger": "USER",
                    "phase": "BEFORE_PUBLICATION",
                    "dataType": "sample",
                    "targetServer": "platformServer",
                    "targetRuntimeRole": "PLATFORM"
                  },
                  {
                    "code": "circa.ewaste:circaLocalOpeningStaffAssignments",
                    "kind": "Circa Local opening Inventory staff assignments",
                    "order": 123,
                    "required": true,
                    "trigger": "USER",
                    "phase": "BEFORE_PUBLICATION",
                    "dataType": "sample",
                    "targetServer": "platformServer",
                    "targetRuntimeRole": "PLATFORM"
                  },
                  {
                    "code": "circa.ewaste:circaGreenPerksOutletCommerce",
                    "kind": "Fictional greenperks outlet goods catalogue",
                    "order": 130,
                    "required": true,
                    "trigger": "USER",
                    "phase": "BEFORE_PUBLICATION",
                    "dataType": "sample",
                    "targetServer": "commerceStaged",
                    "targetRuntimeRole": "COMMERCE_STAGED"
                  },
                  {
                    "code": "circa.ewaste:circaRenewWorksOutletCommerce",
                    "kind": "Fictional renewworks outlet goods catalogue",
                    "order": 131,
                    "required": true,
                    "trigger": "USER",
                    "phase": "BEFORE_PUBLICATION",
                    "dataType": "sample",
                    "targetServer": "commerceStaged",
                    "targetRuntimeRole": "COMMERCE_STAGED"
                  },
                  {
                    "code": "circa.ewaste:circaLoopCycleOutletCommerce",
                    "kind": "Fictional loopcycle outlet goods catalogue",
                    "order": 132,
                    "required": true,
                    "trigger": "USER",
                    "phase": "BEFORE_PUBLICATION",
                    "dataType": "sample",
                    "targetServer": "commerceStaged",
                    "targetRuntimeRole": "COMMERCE_STAGED"
                  },
                  {
                    "code": "circa.ewaste:circaLocalDemoCredit",
                    "kind": "Approved guarded one-time Local demo POINTS credit",
                    "order": 190,
                    "required": true,
                    "trigger": "USER",
                    "phase": "AFTER_PUBLICATION",
                    "operatorEnterpriseCode": "GREENPERKS_ONLINE",
                    "dataType": "sample",
                    "targetServer": "loyaltyServer",
                    "targetRuntimeRole": "LOYALTY"
                  },
                  {
                    "code": "circa.ewaste:circaGreenPerksOutletPublicationPlan",
                    "type": "GOVERNED_PUBLICATIONS",
                    "kind": "Fictional greenperks outlet governed publication",
                    "operatorEnterpriseCode": "GREENPERKS_RETAIL",
                    "order": 200,
                    "required": true,
                    "trigger": "USER",
                    "phase": "AFTER_PUBLICATION",
                    "dataType": "sample",
                    "targetServer": "commerceStaged",
                    "targetRuntimeRole": "COMMERCE_STAGED",
                    "publicationPlan": require("../../../../modules/circa.ewaste/data/sample-v001/merchant-outlets/greenperks/publication/records/publicationPlan.json")
                  },
                  {
                    "code": "circa.ewaste:circaGreenPerksOutletOpening",
                    "kind": "Fictional greenperks Inventory first intake after outlet publication",
                    "operatorEnterpriseCode": "GREENPERKS_RETAIL",
                    "order": 201,
                    "required": true,
                    "trigger": "USER",
                    "phase": "AFTER_PUBLICATION",
                    "dataType": "sample",
                    "targetServer": "commerce",
                    "targetRuntimeRole": "COMMERCE"
                  },
                  {
                    "code": "circa.ewaste:circaRenewWorksOutletPublicationPlan",
                    "type": "GOVERNED_PUBLICATIONS",
                    "kind": "Fictional renewworks outlet governed publication",
                    "operatorEnterpriseCode": "RENEWWORKS_REPAIR_REUSE",
                    "order": 202,
                    "required": true,
                    "trigger": "USER",
                    "phase": "AFTER_PUBLICATION",
                    "dataType": "sample",
                    "targetServer": "commerceStaged",
                    "targetRuntimeRole": "COMMERCE_STAGED",
                    "publicationPlan": require("../../../../modules/circa.ewaste/data/sample-v001/merchant-outlets/renewworks/publication/records/publicationPlan.json")
                  },
                  {
                    "code": "circa.ewaste:circaRenewWorksOutletOpening",
                    "kind": "Fictional renewworks Inventory first intake after outlet publication",
                    "operatorEnterpriseCode": "RENEWWORKS_REPAIR_REUSE",
                    "order": 203,
                    "required": true,
                    "trigger": "USER",
                    "phase": "AFTER_PUBLICATION",
                    "dataType": "sample",
                    "targetServer": "commerce",
                    "targetRuntimeRole": "COMMERCE"
                  },
                  {
                    "code": "circa.ewaste:circaLoopCycleOutletPublicationPlan",
                    "type": "GOVERNED_PUBLICATIONS",
                    "kind": "Fictional loopcycle outlet governed publication",
                    "operatorEnterpriseCode": "LOOPCYCLE_RECYCLING",
                    "order": 204,
                    "required": true,
                    "trigger": "USER",
                    "phase": "AFTER_PUBLICATION",
                    "dataType": "sample",
                    "targetServer": "commerceStaged",
                    "targetRuntimeRole": "COMMERCE_STAGED",
                    "publicationPlan": require("../../../../modules/circa.ewaste/data/sample-v001/merchant-outlets/loopcycle/publication/records/publicationPlan.json")
                  },
                  {
                    "code": "circa.ewaste:circaLoopCycleOutletOpening",
                    "kind": "Fictional loopcycle Inventory first intake after outlet publication",
                    "operatorEnterpriseCode": "LOOPCYCLE_RECYCLING",
                    "order": 205,
                    "required": true,
                    "trigger": "USER",
                    "phase": "AFTER_PUBLICATION",
                    "dataType": "sample",
                    "targetServer": "commerce",
                    "targetRuntimeRole": "COMMERCE"
                  },
                ],
              },
            },
          },
        },
      },
    },
  },
  activeModules: {
    groups: ["nodics.discovery", "nodics.copilot"],
    modules: [
      "publish",
      "redisCache",
      "circa.ewaste",
      "agora.apparel",
      "agora.electronics",
      "agora.telco",
      "nexusCore",
      "search",
      "elastic",
      "nodics.kickoff",
      "kickoffCore",
      "kickoffApi",
      "kickoffInt",
      "axis",
      "ollamaProvider",
    ],
  },
  runtimeRole: {
    code: "PLATFORM",
    publication: "OPERATIONAL",
  },
  database: {
    default: {
      mongodb: {
        master: {
          databaseName: "kickoffLocalPlatform",
        },
      },
    },
  },
  servers: {
    default: {
      endpoint: {
        httpPort: 4300,
        httpsPort: 4301,
      },
    },
  },
};
